server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking-homestay_db
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
